# Generated by Django 4.0.3 on 2022-03-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postimage_image_postimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='posts.post'),
        ),
    ]
