# Generated by Django 4.0.3 on 2022-03-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_buy',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
