name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  test-and-build-server:
    name: Test Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    env:
      SECRET_KEY: '{{ secrets.SECRET_KEY }}'
      EMAIL_HOST_PASSWORD: '{{ secrets.EMAIL_HOST_PASSWORD }}'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make Migrations
      working-directory: ./backend
      run: |
        python manage.py makemigrations
    - name: Run Migrations
      working-directory: ./backend
      run: |
        python manage.py migrate
    - name: Run Tests
      working-directory: ./backend
      run: |
        python manage.py test

  test-and-build-client:
    name: Test Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./mobile
        run: yarn install
      - name: Run Prettier
        working-directory: ./mobile
        run: yarn prettier:check
      - name: Run Lint
        working-directory: ./mobile
        run: yarn lint
  
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dagger Test
        working-directory: .
        run: dagger do test
